baseURL = "https://guojun-dou.github.io/my-blog/"
languageCode = "zh-cn"
title = "my-blog"
theme = "PaperMod"
enableRobotsTXT = true
canonifyURLs = true

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  comments = false
[permalinks]
  posts = "/posts/:slug/"
